name: Test Slack Notification on Failure

on:
  push:
  #   pull_request:
  workflow_dispatch:

jobs:
  simulate-failure:
    name: Simulate Failing Job
    runs-on: ubuntu-latest
    steps:
      - name: Force failure
        run: exit 1

  notify-slack:
    name: Notify Slack on Failure
    needs: [simulate-failure]
    if: ${{ failure() }} # ✅ Ensure it only runs if above job fails
    uses: ./.github/workflows/notify-slack.yml
    with:
      job_name: "Simulated Job"
      run_id: ${{ github.run_id }}
      channel: "ci-cd-alerts"
      error_message: "Simulated job failed in test run"
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
